### ISSUE TITLE
Language in error logging

### ISSUE THREAD

**Issue by alexdelprete** [Miraitowa-la/ModbusLink#2]
Hi,

I'm testing this library for one of my Home Assistant integrations. Thanks for the great work, I like it a lot.

I have an issue with logging: I can see mixed languages in the log when exceptions are caught.

```console
2025-12-07 03:15:32.259 ERROR (MainThread) [custom_components.sinapsi_alfa.api] (_read_batch) [address=30, error=事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 5, 收到 | Received 1]: Data/protocol error
2025-12-07 03:15:32.259 ERROR (MainThread) [custom_components.sinapsi_alfa.api] (_read_batch) [address=203, error=事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 6, 收到 | Received 840]: Data/protocol error
2025-12-07 03:15:32.260 ERROR (MainThread) [custom_components.sinapsi_alfa.api] (_read_batch) [address=780, error=事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 7, 收到 | Received 56]: Data/protocol error
2025-12-07 03:15:32.270 ERROR (MainThread) [custom_components.sinapsi_alfa.api] (_read_batch) [address=921, error=事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 8, 收到 | Received 0]: Data/protocol error
2025-12-07 03:15:32.504 ERROR (MainThread) [custom_components.sinapsi_alfa.api] (read_modbus_alfa) [error=Data error at address 30: 事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 5, 收到 | Received 1]: Failed to read 
```

What do I need to configure to have everything in english?

Thanks,

Alessandro

**Comment by Miraitowa-la** [comment]
Hi Alessandro,

Sorry for the inconvenience caused by the mixed-language logs! Currently, the separate English/Chinese logging isn't supported yet, but we're actively working on it. We plan to roll out a version update to fix this issue next week.

Thank you for your understanding and valuable feedback—we appreciate your support!

Best regards,

**Comment by alexdelprete** [comment]
Your library is working great. I successfully released v1.0.0 of my [integration](https://github.com/alexdelprete/ha-sinapsi-alfa/releases/tag/v1.0.0) that uses it and it's working great; performance was really improved vs when I used pymodbus. Thanks for your work.

**Comment by Miraitowa-la** [comment]
Hi Alessandro,

Congratulations on the v1.0.0 release of your integration! I am thrilled to hear that the performance has improved compared to pymodbus and that the library is working well for you.

Thank you again for raising the logging issue. While I was working on the English/Chinese adaptation to address your request, I actually discovered a hidden bug (#4) and an area that required enhancement (#3). Your feedback was instrumental in helping me identify and fix these additional issues.

The language support is now available in **ModbusLink 1.3.1**. To resolve the mixed-language logging, you just need to set the language parameter during setup:

```Python
ModbusLogger.setup_logging(
    ......
    language=Language.EN
)
```

Thanks for your support!

Best regards,

**Comment by alexdelprete** [comment]
> Congratulations on the v1.0.0 release of your integration! I am thrilled to hear that the performance has improved compared to pymodbus and that the library is working well for you.

thanks for your kind words and for providing this library to the community. I'll recommend it to anyone that asks me for advice.

> Thank you again for raising the logging issue. While I was working on the English/Chinese adaptation to address your request, I actually discovered a hidden bug ([#4](https://github.com/Miraitowa-la/ModbusLink/issues/4)) and an area that required enhancement ([#3](https://github.com/Miraitowa-la/ModbusLink/issues/3)). Your feedback was instrumental in helping me identify and fix these additional issues.

Actually I was going to raise an issue regarding #4 and also #3. :)

For #4 I had noticed some weird random errors in the log, and now I suspect it's due to that bug. I'll test it once it's fixed.

For #3, I noticed that there were missing methods/functions for the async client, but I solved those by doing conversions etc. in the integration code. Would be nice to have async client in par with the sync client.

Hope they will be fixed soon so I can improve the integration.

Thanks a lot for your work!

Warm regards.

Alessandro

**Comment by alexdelprete** [comment]
> The language support is now available in **ModbusLink 1.3.2**.

I issued v1.1.5 of my integration with modbuslink 1.3.2 as requirement. I didn't check the releases of ModbusLink. Unfortunately users that upgraded told me it wasn't starting, and I found out the last release with the language fix was 1.3.1.

Unfortunately though, there's also another issue: 1.3.1 hasn't been released on pypi, so my integration won't start because it doesn't find it. Can you please push it to pypi? Thanks.

**Comment by Miraitowa-la** [comment]
I have released ModbusLink 1.3.1 on PyPI. This was indeed a mistake on my part. Thank you for your reminder. 

The statement "The language support is now available in ModbusLink 1.3.2" was incorrect on my part. The current latest version is 1.3.1, which includes language corrections.

I will also fix problems 3 and 4 as soon as possible.

**Comment by alexdelprete** [comment]
> I have released ModbusLink 1.3.1 on PyPI. This was indeed a mistake on my part. Thank you for your reminder.

Thank you so much, I really appreciate your quick support. I was convinced that pypi release would be automatically pushed through GH Actions.
 
> The statement "The language support is now available in ModbusLink 1.3.2" was incorrect on my part. The current latest version is 1.3.1, which includes language corrections.

No worries, it happened to me in the past. :)
 
> I will also fix problems 3 and 4 as soon as possible.

That would be awesome, thanks.

**Comment by alexdelprete** [comment]
So, I still have issues with the code. This is failing:

```python
from modbuslink import (
    AsyncModbusClient,
    AsyncTcpTransport,
    CRCError,
    InvalidResponseError,
    Language,              # NOT EXPORTED from modbuslink
    ModbusException,
    ModbusLinkError,
    ModbusLogger,          # NOT EXPORTED from modbuslink
)
```

Looks like Language and ModbusLogger classes exist in modbuslink/utils/logging.py but they aren't re-exported in the main modbuslink/__init__.py

Would this work? Or it's better I wait for a fix?

```python
from modbuslink import (
    AsyncModbusClient,
    AsyncTcpTransport,
    CRCError,
    InvalidResponseError,
    ModbusException,
    ModbusLinkError,
)
from modbuslink.utils.logging import Language, ModbusLogger
```

**Comment by Miraitowa-la** [comment]
Because I personally believe that "utils/logging.py" does not fall under the category of the Modbus protocol. It is more like an extension tool. Therefore, I did not include it in "modbuslink/init.py". However, for ease of use, I will add it later.

**Comment by alexdelprete** [comment]
> Because I personally believe that "utils/logging.py" does not fall under the category of the Modbus protocol. It is more like an extension tool. Therefore, I did not include it in "modbuslink/init.py". However, for ease of use, I will add it later.

Don't worry about it, leave it like it is. This works:

```python
from modbuslink.utils.logging import Language, ModbusLogger
```

The only thing I would argue is that ModbusLogger seems kind of like ModbusException, are there "exceptions" in the ModBus protocol?

Anyway, everything's ok now. Thanks again.

**Comment by alexdelprete** [comment]
@Miraitowa-la One other thing. I see bilingual strings in the integration log, they look like exceptions messages:

```console
Logger: custom_components.sinapsi_alfa.api
Source: custom_components/sinapsi_alfa/helpers.py:85
integration: Alfa by Sinapsi (documentation, issues)
First occurred: 19 December 2025 at 22:46:55 (142 occurrences)
Last logged: 18:30:42

(read_modbus_alfa) [error=Data error at address 2: 事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 3627, 收到 | Received 3626]: Failed to read modbus data
(_read_batch) [address=2, error=事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 3634, 收到 | Received 3633]: Data/protocol error
(read_modbus_alfa) [error=Data error at address 2: 事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 3634, 收到 | Received 3633]: Failed to read modbus data
(_read_batch) [address=2, error=事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 3671, 收到 | Received 3670]: Data/protocol error
(read_modbus_alfa) [error=Data error at address 2: 事务ID不匹配 | Transaction ID mismatch: 期望 | Expected 3671, 收到 | Received 3670]: Failed to read modbus data
```

**Comment by Miraitowa-la** [comment]
I took a look at this because I only made the Chinese-English corrections for the "log system" (src/modbuslink/utils/logging.py) file, but I did not make the corrections for the "error module" (src/modbuslink/common/exceptions.py). 

Thank you for your feedback. I will fix it as soon as possible.

**Comment by alexdelprete** [comment]
> Thank you for your feedback. I will fix it as soon as possible.

No worries. So, the language setting scope will be both for logging and errors, correct?

**Comment by Miraitowa-la** [comment]
At present, the "error module" cannot be set to a specific language yet; they are still all mixed together. 

I'm thinking whether to set it up separately or as a unified whole.

**Comment by Miraitowa-la** [comment]
"ModbusLink 1.3.2" has been updated and the following issues have been resolved:

1. The problem of mixed Chinese and English in the "Error Module" has been resolved (of course, there might still be some areas that I haven't noticed).

2. You can directly use modbuslink to call the content in "logging.py" now.
```Python
from modbuslink import Language, ModbusLogger
```

3. New language setting method, which takes effect on both logs and errors
```Python
from modbuslink import Language, set_language

# Set as English
set_language(Language.EN)

# Set to Chinese (default)
set_language(Language.CN)
```
```Python
from modbuslink import Language, ModbusLogger
import logging

ModbusLogger.setup_logging(
    level=logging.DEBUG,
    enable_debug=True,
    log_file='modbus_debug.log'
    # language=Language.EN # This attribute remains retained (globally)
)
```

**Comment by alexdelprete** [comment]
Thanks a lot.
